#!/bin/bash
#!/bin/bash
#SBATCH --job-name=experiment1
#SBATCH -N1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=15
#SBATCH -p EPYC
#SBATCH --mem=50gb
#SBATCH --time=40:00:00
#SBATCH --output=slurm_log/euvsdisinfo1.log
#SBATCH --error=slurm_log/euvsdisinfo1.log

cd src/euvsdisinfo_scraping/
poetry run python scripts/collect/collect.py --api_token=3388fb30431045b747503222af6a006b --num_processes=10
poetry run python test_progress.py 